"""first revision

迁移 ID: b8ea6b54985c
父迁移:
创建时间: 2025-12-20 06:48:47.557831

"""

from __future__ import annotations

from collections.abc import Sequence

revision: str = "b8ea6b54985c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ("quick_reply",)
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
